### ISSUE TITLE
Unresponsive Prometheus Host

### ISSUE THREAD

**Issue by sukhmancs** [NotAShelf/nyx#69]
I'm uncertain whether it's a problem or simply due to my limited familiarity with NixOS. After adjusting configurations to enable Prometheus on my computer, whenever I attempt tasks related to 'ags', my system experiences resource overload. It seems 'ags' spawns excessive processes simultaneously. Additionally, despite changing locale and keyboard settings to Canada and Dvorak, my keyboard layout remains unresponsive, preventing me from launching applications like launchers. Apologies if this sounds more like a request for assistance than an issue report.

**Correction**: `nyx/hosts/hermes/encryption.nix` is duplicate of `modules/core/common/system/encryption/default.nix`. 

Thank you

**Comment by NotAShelf** [comment]
Prometheus host is deprecated.

**Comment by NotAShelf** [comment]
Please consider writing your own config. I will not (be able to) aid with "I copied your configuration and changed it, now it doesn't work!" kinds of issues. 

ags spawning multiple processes is probably a quirk of python. I've been meaning to replace it for a while, simply didn't have the time.

About encryption, yes the host module and the common module are duplicates.That is because the encryption module is not yet complete.

**Comment by sukhmancs** [comment]
Thanks for reaching out. Apologies for any confusion. My intention was to initiate the setup process with a base configuration using flake-parts. Also, I'm looking to set up greetd with a Dvorak layout. I've tried adjusting Xorg settings but haven't had success. Any guidance on what needs changing? 

Thanks a bunch.

**Comment by NotAShelf** [comment]
If you haven't changed the greeter, it would probably be adjusted via tuigreet args. 

Since I don't use dvorak, I also don't know how to change it.
