### ISSUE TITLE
Setting up Leto Host in QEMU

### ISSUE THREAD

**Issue by sukhmancs** [NotAShelf/nyx#73]
This is not an issue; I just need some help setting up the `leto` host. I am trying to configure `leto` host in QEMU, but every time I attempt to boot into this configuration, I am unable to boot into the VM. Here are the steps I followed: first, I performed a standard NixOS installation. Then, I attempted to boot into the `leto` host after changing some settings, such as disabling swap.

__Is leto host deprecated?__ Could you please share the steps you use to boot into such a host when using virtual machines like QEMU? It would be really helpful if you could also provide the commands. Thank you, as always. You can close this issue without replying if that's more convenient, but I appreciate your help either way.

Thank you

**Comment by NotAShelf** [comment]
In addition:
- You copying my configuration as is, then pretending you have done something is disrespectful to my time and efforts ("some of the features that I have implemented in this configuration", where none of the things you have changed are, quote, features)
- I have previously mentioned that I will *not* be aiding with support requests such as "I changed something in *your* configuration, and now it doesn't work". **Do write your own, from scratch** and then I am willing to aid you.

Please don't be the person that prompts me to take this configuration private. I appreciate that you've *at least* shown the courtesy of forking instead of downloading and pushing, but what you are doing (*pretending* you have done something other than landing on a largely active repository) is disrespectful. If you wish to copy my configuration, you will be on your own. I do not have the responsibility to you, or to anyone else, to spend the time explaining my **personal configuration** to people who think it belongs to them.
